### ISSUE TITLE
พี่ครับๆ เกมนี้มีในโทรศัพท์ไหมครับ

### ISSUE THREAD

**Issue by golfcap45** [Thawin2077/LineBot-GoogleSheet#1]
ผม ผม เล่นในโทรศัพท์ได้ไหมครับ สเปคเท่านี้เล่นได้ไหมคับพี่ช่วยดูให้หน่อยได้ไหมครัฟ

**Comment by Thawin2077** [comment]
ต....แต่ มันไม่ใช่เกมส์ครับน้อง !!
